nri-bundle:
  global:
    cluster: jchen-au-gke-main
    customSecretName: newrelic-api-keys
    customSecretLicenseKey: license-key
  newrelic-infrastructure:
    kubelet:
      resources:
        requests:
          cpu: 0
    ksm:
      resources:
        requests:
          cpu: 0
  nri-metadata-injection:
    resources:
      requests:
        cpu: 0
  kube-state-metrics:
    enabled: true
