ingress-nginx:
  controller:
    electionID: ingress-nginx-public
    ingressClassResource:
      enabled: true
      name: ingress-nginx-public
      default: false
      controllerValue: k8s.io/ingress-nginx-public
    extraArgs:
      default-ssl-certificate: "tls-certificates/wildcard-jchen-au"
