{{- range $name, $config := .Values.apps }}
{{- if ne ($config.enabled | quote) "false" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
spec:
  destination:
    namespace: {{ $config.namespace | default $name }}
    server: https://kubernetes.default.svc
  project: {{ .project | default "default" }}
  source:
    {{- if $config.path }}
    path: {{ $config.path }}
    {{- else }}
    path: "charts/{{ $name }}"
    {{- end }}

    {{- if $config.repoURL }}
    repoURL: {{ $config.repoURL }}
    {{- else }}
    repoURL: {{ $.Values.global.repoURL }}
    {{- end }}

    targetRevision: {{ $config.targetRevision | default "HEAD" }}

    helm:
      valueFiles:
      {{- if $config.valueFiles }}
        {{- range $config.valueFiles }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- if $config.skipCrds }}
      skipCrds: {{ $config.skipCrds }}
      {{- end }}

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

  {{- with $config.ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
