argo-cd:
  server:
    ingress:
      enabled: true
      ingressClassName: ingress-nginx-public
      hosts:
        - argocd.jchen.au
  applicationSet:
    enabled: false
  notifications:
    enabled: false
